### ISSUE TITLE
Allow to configure test name in selecting Relationships

### ISSUE THREAD

**Issue by datnguye** [datnguye/dbterd#27]
**Is your feature request related to a problem? Please describe.**
If dbt project was using [dbt_constraints](https://github.com/Snowflake-Labs/dbt_constraints), they're using the test named `foreign_key`. 

**Describe the solution you'd like**
We should support that with the configurable input of the test name. Default test name containing `relationship` wording.

**Describe alternatives you've considered**
N/A

**Additional context**
Sample usage of the dbt-contrainst package:
```
  - name: DIM_ORDER_LINES
    columns:
      # Single column inline constraints
      - name: OL_PK
        tests:
          - dbt_constraints.primary_key
      - name: OL_UK
        tests:
          - dbt_constraints.unique_key
      - name: OL_CUSTKEY
        tests:
          - dbt_constraints.foreign_key:
              pk_table_name: ref('DIM_CUSTOMERS')
              pk_column_name: C_CUSTKEY
```
