### ISSUE TITLE
[FEAT] Select criteria using tags in models

### ISSUE THREAD

**Issue by philiphagglund** [datnguye/dbterd#57]
**Is your feature request related to a problem? Please describe.**
It seems not to be possible to select models by using one or multiple tag.

**Describe the solution you'd like**
Adding the functionality to run `dbterd` over tags specified in models metadata. 
``` 
models:
  - name: test
    config:
      materialized: incremental
      tags: test, test2
    columns:
      - name: test_key
        tests:
          - relationships_test:
              to: ref('test2')
              field: test_key
``` 
`dbterd run -ad target -s tag:test` 
or a list of tags  
`dbterd run -ad target -s tag:test,test2`
