### ISSUE TITLE
[BUG] ER diagram is not output when node_name is capitalized

### ISSUE THREAD

**Issue by syou6162** [datnguye/dbterd#73]
**Describe the bug**
ER diagram is not output when `node_name` is capitalized.

**To Reproduce**
Our data source is exported from firebase, so our data source has capitalized table names.

```yaml
version: 2
sources:
  - name: my_model
    database: my-project
    tables:
      - name: User
      ...
```

Running `dbterd run` in this case will only output `erDiagram` in `target/output.md` and will fail to generate an ER diagram.

```
% dbterd run -t mermaid --entity-name-format schema.table \
  --resource-type source \
  --select exact:source.my_model.firestore_export.User
```

**Expected behavior**
Generation of target ERD

**Desktop (please complete the following information):**

- OS: macOS Monterey
- Version: 1.9.1

**Additional context**
